"""Regenerate every Kaggle notebook from tyrelib.py.

The .py file is the SOURCE OF TRUTH. The notebooks are generated. Edit Python,
run this, re-upload. Never hand-edit the base64 blob inside a notebook.
"""
import base64, json, math, sys
from pathlib import Path

HERE = Path(__file__).parent
LIB = HERE / "tyrelib.py"
# The generated notebooks live beside `tyrelib/`, not inside it.  The old
# default silently created `tyrelib/notebooks/`, while the files the user
# uploads are `<project>/notebooks/`. An explicit argv path still wins.
OUT = Path(sys.argv[1]) if len(sys.argv) > 1 else HERE.parent / "notebooks"
OUT.mkdir(parents=True, exist_ok=True)

sys.path.insert(0, str(HERE))
import tyrelib as T

# ---------------------------------------------------------------- bootstrap
def bootstrap_cell() -> str:
    b64 = base64.b64encode(LIB.read_bytes()).decode()
    chunks = [b64[i:i+96] for i in range(0, len(b64), 96)]
    lib_lit = "_LIB = (\n" + ",\n".join(f"    '{c}'" for c in chunks) + ",\n)\n"
    return f'''# === CELL 1 of every notebook: unpack the library ==========================
# Writes tyrelib.py into the session and imports it. Nothing here touches the
# GPU or the network beyond installing three small packages.
#
#   tyrelib   the whole pipeline: HuggingFace sync, registry, work sharding,
#             telemetry, model zoo, training loop, metrics.
#
# Generated by build_notebooks.py from tyrelib.py. Editing the blob below does
# nothing useful -- the next rebuild overwrites it. Edit the source instead.
import base64, subprocess, sys
from pathlib import Path

WORK = Path('/kaggle/working') if Path('/kaggle/working').is_dir() else Path.cwd()

# Kaggle ships torch, pandas, sklearn. These vary by image version, so check.
#   pynvml  reads GPU power/temperature/clocks directly (per device)
#   psutil  peak RAM and CPU
#   pyarrow writes per-sample predictions as Parquet
for _pkg in ('pynvml', 'psutil', 'pyarrow', 'timm'):
    try:
        __import__(_pkg)
    except ImportError:
        print(f'[BOOT] installing {{_pkg}} ...')
        subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', _pkg],
                       check=False)

{lib_lit}
(WORK / 'tyrelib.py').write_bytes(base64.b64decode(''.join(_LIB)))
if str(WORK) not in sys.path:
    sys.path.insert(0, str(WORK))
# Without this, re-running cell 1 after an edit returns the cached module and
# you spend an hour debugging a ghost.
for _m in [m for m in list(sys.modules) if m == 'tyrelib']:
    del sys.modules[_m]
import tyrelib as tl
print('tyrelib', tl.__version__, 'loaded')
'''

def md(s):   return {"cell_type": "markdown", "metadata": {}, "source": s.splitlines(True)}
def code(s): return {"cell_type": "code", "execution_count": None, "metadata": {},
                     "outputs": [], "source": s.splitlines(True)}

def write_nb(name, cells):
    nb = {"cells": cells,
          "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
                       "language_info": {"name": "python", "version": "3.11.13"},
                       "accelerator": "GPU",
                       "kaggle": {"accelerator": "nvidiaTeslaT4",
                                  "dataSources": [{"sourceType": "datasetVersion",
                                                   "reference": "shanmuk4622/tire-dataset-prepared"}],
                                  "isGpuEnabled": True, "isInternetEnabled": True,
                                  "language": "python", "sourceType": "notebook"}},
          "nbformat": 4, "nbformat_minor": 5}
    p = OUT / name
    p.write_text(json.dumps(nb, indent=1))
    # verify the blob round-trips byte-identically -- a silent truncation here
    # means you debug the wrong code for an hour
    blob = "".join(json.loads(p.read_text())["cells"][1]["source"])
    lit = blob.split("_LIB = (")[1].split(")\n")[0]
    got = base64.b64decode("".join(eval("(" + lit + ")")))
    assert got == LIB.read_bytes(), f"BASE64 ROUND-TRIP FAILED in {name}"
    print(f"  {name:<34} {p.stat().st_size/1024:6.0f} KB  {len(cells):2d} cells  b64 OK")

# ---------------------------------------------------------------- headers
def budget_md(archs, folds=3, seeds=3, extra=""):
    ids = [f"a-{a}-base-f{f}-s{s}" for a in archs for f in range(folds) for s in range(seeds)]
    tot_h = sum(T.cost_of(i) for i in ids) / 60
    rows = "\n".join(
        f"| `{a}` | {T.ZOO[a]['res']} | {T.ZOO[a]['bs']} | {T.RECIPE['max_epochs']} | "
        f"{T.STATIC_COST_HINTS.get(a, T.DEFAULT_COST):.0f} min | "
        f"{T.STATIC_COST_HINTS.get(a, T.DEFAULT_COST)*folds*seeds/60:.1f} h |"
        for a in archs)
    wall = "\n".join(
        f"| {nw} | ~{T.estimate_phase(ids, nw)['wall_clock_hours']:.1f} h | "
        f"{T.estimate_phase(ids, nw)['sessions_needed']} |"
        for nw in (1, 2, 4) if nw <= len(ids))
    return f"""
## What this notebook runs

| | |
|---|---|
| **Architectures** | {len(archs)} |
| **Folds x seeds each** | {folds} x {seeds} = {folds*seeds} |
| **Total training runs** | **{len(ids)}** |
| **Estimated GPU time** | **~{tot_h:.0f} GPU-hours** |

### Wall-clock, by how many Kaggle accounts you run

| NUM_WORKERS | Wall-clock | Kaggle sessions each |
|---|---|---|
{wall}

### Per architecture

| Architecture | Res | Batch | Epochs | Est. per run | x {folds*seeds} runs |
|---|---|---|---|---|---|
{rows}

> Estimates come from a **static** cost table calibrated against measured T4
> throughput. It stays static on purpose: if measurements fed back into the
> work split, two workers planning at different times would disagree about
> what they own, and a job gets trained twice while another is abandoned.

> **No early stopping.** Every run trains the full {T.RECIPE['max_epochs']}-epoch budget. Equal
> budget for every architecture is what keeps the comparison fair, and it means
> a run's length is known in advance -- which is what makes the estimate above
> honest.

> A Kaggle session lasts ~9-12 h and this pipeline pauses cleanly at 8.5 h, so a
> run needing more than one session resumes automatically. Just start a fresh
> session and re-run the notebook.
{extra}
"""

SESSION_CELL = '''# === Who am I? =============================================================
#
# ACCOUNT   labels this Kaggle account in the shared run log. Two accounts
#           calling themselves the same thing makes the log useless.
# NUM_WORKERS  how many Kaggle accounts are running this notebook in parallel.
# WORKER_ID    0 .. NUM_WORKERS-1, DIFFERENT on each account.
#
# ---------------------------------------------------------------------------
# THESE TWO VALUES ARE SAFE TO CHANGE AT ANY TIME.
#
# They decide which account owns each fresh run. An absent or partial run stays
# with that static owner. Work stealing is disabled by default; an explicit
# recovery run may opt in and can then take over only a real claim/run event
# older than 45 minutes. Whether a run is finished, and what epoch it reached,
# is read from HuggingFace -- from the run's own files -- so it is the same
# answer for every account at every worker count.
# Go from 4 workers to 1 and nothing is retrained: the runs the other three
# finished are skipped, and the ones they left half-done are RESUMED from
# their checkpoints.
#
# (It did not always work that way. Resume used to check only the local disk,
#  and Kaggle wipes that between sessions, so every run restarted at epoch 1.
#  See docs/05 -- Bug 8.)
# ---------------------------------------------------------------------------
#
# All accounts push to the SAME HuggingFace account (Shanmuk4622), so the
# 128-writes-per-hour budget is SHARED. tyrelib caps each worker at
# 100/NUM_WORKERS automatically.
ACCOUNT     = 'acct1'   # <<< acct1 / acct2 / acct3 / acct4 on the four copies
NUM_WORKERS = 4         # <<< set 1 only when you are really running one notebook

# Derive the worker id from the account label so changing ACCOUNT is enough.
# This prevents four copies that all silently identify themselves as worker 0.
_ACCOUNT_TO_WORKER = {'acct1': 0, 'acct2': 1, 'acct3': 2, 'acct4': 3}
if ACCOUNT not in _ACCOUNT_TO_WORKER:
    raise ValueError(f"ACCOUNT must be one of {list(_ACCOUNT_TO_WORKER)}, got {ACCOUNT!r}")
WORKER_ID = _ACCOUNT_TO_WORKER[ACCOUNT]
if WORKER_ID >= NUM_WORKERS:
    raise ValueError(f"{ACCOUNT} maps to worker {WORKER_ID}, outside NUM_WORKERS={NUM_WORKERS}. "
                     "For a one-notebook run use acct1; for four use acct1..acct4.")

sess = tl.Session(account=ACCOUNT, worker_id=WORKER_ID, num_workers=NUM_WORKERS,
                  stage='a',
                  hf_repo='Shanmuk4622/tyre-wear-study',
                  enable_hf=True,
                  session_limit_h=8.5,      # push + pause before Kaggle kills us
                  push_interval_min=30)     # background commit cycle
'''

DATA_CELL = '''# === Find the dataset ======================================================
# One Kaggle dataset holds the whole package:
#     <slug>/FINAL/{images,splits,manifests}
#     <slug>/annotations/{clean,propagated}
# Kaggle sometimes wraps uploads in one more directory, so both are searched for.
DATA_ROOT = sess.prepare_data()
ANN_ROOT  = tl.find_annotations_root(DATA_ROOT)
print("annotations:", ANN_ROOT if ANN_ROOT else "NOT FOUND (only needed from NB08 onward)")
'''

SYNC_CELL = '''# === Catch up with what every account has already done =====================
# Two different questions, answered by two different sources.
#
#   registry   who CLAIMED what. Per-worker shard files, because HuggingFace
#              has no append and a shared ledger would silently lose writes.
#              Useful for one thing only: is somebody on this run right now.
#
#   inventory  what the repository actually HOLDS. runs/<id>/STATUS.json either
#              says epoch 34 or it does not, and it says the same thing to
#              every account at every value of NUM_WORKERS.
#
# Work planning reads the inventory. That is what makes the worker count safe
# to change.
sess.sync_state(verbose=True)
sess.push_now('sync complete')       # <- push at the end of an important cell
'''

FINISH_CELL = '''# === Push everything and stop ==============================================
# Blocks until HuggingFace confirms. Safe to re-run.
sess.finish()

# Draining the upload queue is NOT the same as the files being on HuggingFace.
# Ask the repository before you close this tab.
#
# Three states, not two. FINISHED and RESUMABLE are both safe -- a run paused
# at epoch 34 whose ckpt_last.pt is on HF loses nothing when you close the tab.
# Only AT RISK (no summary.json AND no checkpoint) needs action.
sess.confirm_on_hf(run_ids)
'''


# ==========================================================================
# NB00 -- Preflight
# ==========================================================================
def nb00():
    c = [md("""# NB00 — Preflight

**Run this on every account before anything else.** It is the cheapest place to
find expensive mistakes.

Nine hours of training with nowhere to save it, an architecture that cannot
accept 384px, a resume that silently loses RNG state — every one of those is
found here in ten minutes instead of on day three.

| Check | Failure it prevents |
|---|---|
| `HF_TOKEN` present **and writable** — push a probe, then **re-list the repo** | Training all day with nowhere to save it |
| Dataset attached and integrity-checked | Silent fallback to a slow or wrong path |
| Library selftest (offline, no GPU, no network) | Broken sharding / metrics / rate limiter |
| **Every model builds, forwards, backprops** at its resolution | Shape errors discovered mid-sweep |
| **Kill-and-resume equivalence** | A resumed run that is not equivalent to an uninterrupted one |
| Work split printed with hours per worker | One account working 3× longer than another |

**Runtime: ~10–14 minutes.** Model building dominates (it downloads weights).
"""),
        code(bootstrap_cell()),
        md("## Step 1 — Library selftest (offline, no GPU, no network)"),
        code("""# ~2 seconds. If any of this fails, nothing below is trustworthy.
assert tl.selftest(), 'tyrelib selftest FAILED -- stop here'
"""),
        md("## Step 2 — Session and HuggingFace write access"),
        code(SESSION_CELL),
        code("""# === Is the token actually WRITABLE? =======================================
# ~30 s. A token with read scope authenticates fine and then fails at the first
# commit, nine hours later. Push a probe and re-list the repo to be sure.
from pathlib import Path
import json, time
probe = Path('/kaggle/working/preflight_probe.json')
probe.write_text(json.dumps({'account': ACCOUNT, 'worker': WORKER_ID, 'ts': time.time()}))
sess.uploader.enqueue(probe, f'preflight/{ACCOUNT}_w{WORKER_ID}.json', force=True)
ok = sess.uploader.flush(reason='preflight probe')
missing = sess.uploader.verify_present([f'preflight/{ACCOUNT}_w{WORKER_ID}.json'])
print()
print('flush returned :', ok)
print('missing on HF  :', missing)
assert sess.uploader.enabled is False or not missing, 'HF WRITE FAILED -- fix the token before training'
print('\\nHF write access CONFIRMED' if not missing else '\\nHF disabled (local-only mode)')
"""),
        md("## Step 3 — Dataset"),
        code(DATA_CELL),
        code("""# === Dataset integrity ====================================================
# ~20 s. These are the assertions that matter: a session leak or an augmented
# image in validation would make every number in the study meaningless, and
# both are silent.
import pandas as pd
for fold in (0, 1, 2):
    tr, va = tl.load_split(DATA_ROOT, fold)          # asserts inside
    print(f'fold {fold}:  train {len(tr):>5}  val {len(va):>4}  '
          f'train_sessions {tr.session_group.nunique()}  val_sessions {va.session_group.nunique()}')
print('\\nno session leakage, validation is clean originals only -- all folds\\n')

clean = tl.read_manifest(DATA_ROOT / 'manifests/clean_manifest.csv')
print('clean images :', len(clean), ' sessions:', clean.session_group.nunique())
print(clean.groupby(['proxy_label']).size().to_string())
print()
print('THE SAMPLE SIZE IS', clean.session_group.nunique(), 'TYRES -- not', len(clean), 'images.')
"""),
        md("""## Step 4 — Every model builds, forwards, backprops

At the resolution it will actually see. An architecture that cannot accept its
configured input is the classic mid-sweep failure — and `swin`/`coatnet` are
fixed-window at 224, which is exactly the trap."""),
        code("""# ~6-9 min on first run (downloads pretrained weights), ~40 s afterwards.
import torch, pandas as pd
dev = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
rows = []
for arch, spec in tl.ZOO.items():
    r = {'arch': arch, 'res': spec['res'], 'bs': spec['bs'], 'fixed_224': arch in tl.FIXED_224}
    try:
        m = tl.build_model(arch, 3, pretrained=True, head='coral').to(dev)
        x = torch.randn(2, 3, spec['res'], spec['res'], device=dev)
        y = torch.tensor([0, 2], device=dev)
        out = m(x)
        loss = tl.CoralHead.loss(out, y)
        loss.backward()                                  # forward AND backward
        gp = sum(1 for p in m.parameters() if p.grad is not None)
        r.update(ok=True, out_shape=tuple(out.shape),
                 params_M=round(sum(p.numel() for p in m.parameters())/1e6, 1),
                 grads=gp, err='')
        del m, x, out, loss
        torch.cuda.empty_cache()
    except Exception as e:
        r.update(ok=False, out_shape=None, params_M=None, grads=0, err=f'{type(e).__name__}: {e}'[:70])
    rows.append(r)
    print(('  OK   ' if r['ok'] else '  FAIL ') + f"{arch:<14} {r.get('out_shape')}  {r.get('err','')}")
zoo_df = pd.DataFrame(rows)
print()
print(zoo_df.to_string(index=False))
n_bad = int((~zoo_df.ok).sum())
print(f'\\n{len(zoo_df)-n_bad}/{len(zoo_df)} architectures build, forward and backprop.')

# THIS RAISES. It used to print a line of advice and carry on.
#
# On 26 August it printed exactly this:
#     FAIL dinov2_s  AssertionError: Input height (392) doesn't match model (518).
#     FAIL dinov2_b  AssertionError: Input height (392) doesn't match model (518).
#     17/19 architectures build...
#     Exclude the failures from the sweep, or fix them, BEFORE Stage A.
# and then returned success. Two days later four Kaggle accounts spent a
# session on NB05 discovering the same two lines, at a cost of 18 runs.
#
# A preflight that reports but does not block is not a preflight. If you
# genuinely want to proceed without an architecture, remove it from ZOO --
# which is a decision, recorded in the source, rather than a warning nobody
# scrolled back to.
if n_bad:
    raise RuntimeError(
        f'{n_bad} architecture(s) cannot run at their configured resolution:\\n'
        + zoo_df[~zoo_df.ok][['arch','res','err']].to_string(index=False)
        + '\\n\\nFix them or remove them from tl.ZOO before Stage A. Every run of a\\n'
          'broken architecture fails on its first batch -- and 27 such runs still\\n'
          'look like a notebook that ran to completion.')
"""),
        md("""## Step 5 — Kill-and-resume equivalence

**The important one.** Do not test resume by training a shorter run and asking
for more epochs — that is a clean completion followed by an extension, a
completely different code path that never touches the interrupt handler or the
paused state.

We kill a run for real mid-training, resume it in a fresh call, and compare the
**per-epoch loss after the seam**. Post-seam loss is where a lost RNG state
shows up; final accuracy can match by luck, the loss curve cannot."""),
        code("""# ~3-4 min. Uses resnet18 at 224 with 4 epochs to stay quick.
import shutil, pandas as pd
from pathlib import Path

def _clean(rid):
    d = Path(sess.stage_dir) / 'runs' / rid
    if d.exists():
        shutil.rmtree(d)

base = dict(arch='resnet18', fold=0, seed=1, technique='resumetest', stage='pre')
cfg_ref = sess.config(**base, max_epochs=4, input_resolution=224, batch_size=32, warmup_epochs=1)
cfg_ref['run_id'] = 'pre-resnet18-resumetest-ref'
_clean(cfg_ref['run_id'])
print('--- reference: 4 epochs uninterrupted ---')
tl.Trainer(cfg_ref, sess).run()
ref = pd.read_csv(Path(sess.stage_dir)/'runs'/cfg_ref['run_id']/'metrics'/'epochs.csv')

cfg_cut = dict(cfg_ref); cfg_cut['run_id'] = 'pre-resnet18-resumetest-cut'
_clean(cfg_cut['run_id'])
print('\\n--- interrupted: 2 epochs, then a real kill ---')
c2 = dict(cfg_cut); c2['max_epochs'] = 2
tl.Trainer(c2, sess).run()
print('\\n--- resumed: fresh Trainer, same config, continue to 4 ---')
tl.Trainer(cfg_cut, sess).run()
cut = pd.read_csv(Path(sess.stage_dir)/'runs'/cfg_cut['run_id']/'metrics'/'epochs.csv')

cmp = pd.DataFrame({'epoch': ref.epoch, 'ref_loss': ref.train_loss,
                    'resumed_loss': cut.train_loss.values[:len(ref)]})
cmp['abs_diff'] = (cmp.ref_loss - cmp.resumed_loss).abs()
cmp['post_seam'] = cmp.epoch > 2
print()
print(cmp.to_string(index=False))
post = cmp[cmp.post_seam].abs_diff.max()
print(f'\\nmax |diff| AFTER the seam: {post:.5f}')
print('PASS -- resume is equivalent' if post < 0.05 else
      'FAIL -- resume diverges. Check RNG/scaler/scheduler restore before training anything.')
"""),
        md("## Step 6 — The work split, before committing hours to it"),
        code("""# instant. If this looks badly unbalanced, or the hours are more than you want
# on one account, change NUM_WORKERS now rather than discovering it on day three.
ARCHS = [a for a in tl.ZOO if a != 'resnet18']
run_ids = [f'a-{a}-base-f{f}-s{s}' for a in ARCHS for f in (0,1,2) for s in (1,2,3)]

est = tl.estimate_phase(run_ids, num_workers=NUM_WORKERS)
print(f"Stage A total        : {est['n_runs']} runs, ~{est['total_gpu_hours']:.0f} GPU-hours")
print(f"at NUM_WORKERS={NUM_WORKERS:<2d}     : ~{est['wall_clock_hours']:.1f} h wall-clock "
      f"({est['sessions_needed']} Kaggle session(s) on this account)")
print()
for nw in (1, 2, 4):
    e = tl.estimate_phase(run_ids, nw)
    print(f'  NUM_WORKERS={nw}: ~{e["wall_clock_hours"]:5.1f} h wall-clock'
          + ('   <-- you' if nw == NUM_WORKERS else ''))
print()
rep = tl.shard_report(run_ids, max(NUM_WORKERS, 4))
print(rep.to_string(index=False))
print(f'imbalance: {rep.attrs.get("imbalance")}x  (LPT bin packing; 1.0 is perfect)')
"""),
        md("## Step 7 — Report and push"),
        code("""print('='*66)
print('PREFLIGHT COMPLETE')
print('='*66)
print(f'  account            : {ACCOUNT}  worker {WORKER_ID}/{NUM_WORKERS}')
print(f'  HuggingFace        : {"writable" if sess.uploader.enabled else "DISABLED"}')
print(f'  dataset            : {DATA_ROOT}')
print(f'  architectures OK   : {int(zoo_df.ok.sum())}/{len(zoo_df)}')
print(f'  resume equivalence : {"PASS" if post < 0.05 else "FAIL"}')
print(f'  rate cap           : {sess.uploader.limiter.limit}/hr (shared token)')
print('='*66)
print('\\nBaselines every model must beat (macro-F1, mean over 3 folds):')
print(tl.baseline_table().to_string(index=False))

sess.uploader.enqueue_dir(sess.stage_dir/'runs', 'preflight/runs', force=True)
sess.finish()

# Same rule as the architecture check: a preflight that reports a failure and
# returns normally has told you nothing you will act on. The 26 August run
# printed 'resume equivalence : FAIL' and was read as a pass.
if post >= 0.05:
    raise RuntimeError(
        f'Resume equivalence FAILED (post-seam loss gap {post:.4f}, want < 0.05).\\n'
        'A resumed run is not equivalent to an uninterrupted one, so every\\n'
        'interrupted run in the study is a different experiment from the ones\\n'
        'that were not interrupted. Fix before Stage A.')
""")]
    write_nb("NB00_Preflight.ipynb", c)


# ==========================================================================
# NB01 -- Baselines (Stage S1, Tier 0)
# ==========================================================================
def nb01():
    c = [md("""# NB01 — Baselines: the floor every model must beat

**Runtime: ~12–18 minutes. CPU is enough.**

Before a single neural network is trained, we establish what a *deliberately
stupid* model achieves on this data. This is not a formality — it is the most
important number in the study.

Two probes on the dataset's own group folds:

| Baseline | fold 0 | fold 1 | fold 2 | mean |
|---|---:|---:|---:|---:|
| **Colour only** — 10 statistics from a 64×64 thumbnail | **0.952** | 0.399 | 0.123 | **0.491** |
| **Structure only** — 9 contrast-normalised tread-band statistics | 0.354 | 0.119 | **0.976** | **0.483** |
| Majority class (accuracy) | 0.360 | 0.484 | 0.423 | 0.423 |

**Ten colour numbers score 95.2% on fold 0.** If a ConvNeXt is trained and
fold 0 is reported, it will have reproduced what mean RGB already achieves.

The two probes win on **opposite** folds. That is the fingerprint of memorising
individual tyres rather than learning wear — with one to two sessions per class
per fold, the class label is very nearly a tyre identifier.

**Consequences, which hold for the entire study:**

1. Never report a single fold. Always all three, mean ± spread.
2. Any model must beat **~0.49 mean macro-F1** to have learned anything the
   trivial baselines had not.
3. These lines go on every accuracy figure in the paper.

This notebook re-runs both probes from the raw images so the numbers are
reproducible, and adds HOG+SVM (comparable to Petrovic et al. 2025) and a
random-initialised CNN (which isolates how much comes from transfer alone).
"""),
        code(bootstrap_cell()),
        md("## Step 1 — Session and dataset"),
        code(SESSION_CELL.replace("stage='a'", "stage='s1'")),
        code(DATA_CELL),
        md("""## Step 2 — Extract features

Two deliberately weak feature sets.

**Colour** — mean R/G/B, brightness, contrast, saturation, a blue-excess
fraction (the factory paint stripe on new tyres), a bright-pixel fraction
(pale dust) and a dark-pixel fraction (deep groove shadow). From a 64×64
thumbnail. No texture at all.

**Structure** — from the centre tread band only, with global brightness and
contrast normalised away: groove-shadow fractions at three thresholds, gradient
energy, Laplacian variance, and vertical/horizontal banding strength."""),
        code("""# ~6-9 min for 418 images (decode-bound, not compute-bound).
import numpy as np, pandas as pd
from PIL import Image
from pathlib import Path
from tqdm.auto import tqdm

clean = tl.read_manifest(DATA_ROOT / 'manifests/clean_manifest.csv')

def colour_feats(p):
    a = np.asarray(Image.open(p).convert('RGB').resize((64, 64)), np.float32) / 255.
    mx, mn = a.max(2), a.min(2)
    sat = np.where(mx > 0, (mx - mn) / (mx + 1e-6), 0)
    g = a.mean(2)
    return dict(R=a[...,0].mean(), G=a[...,1].mean(), B=a[...,2].mean(),
                bright=g.mean(), contrast=g.std(), sat=sat.mean(),
                sat_p99=float(np.percentile(sat, 99)),
                blueish=float(((a[...,2]-a[...,0]) > 0.10).mean()),   # paint stripe
                bright_frac=float((g > 0.62).mean()),                  # pale dust
                dark_frac=float((g < 0.18).mean()))                    # groove shadow

def _grad(g):
    gx, gy = np.zeros_like(g), np.zeros_like(g)
    gx[:,1:-1] = g[:,2:]-g[:,:-2]; gy[1:-1,:] = g[2:,:]-g[:-2,:]
    return np.hypot(gx, gy)

def struct_feats(p):
    im = Image.open(p).convert('L'); w, h = im.size
    im = im.crop((int(w*.28), int(h*.28), int(w*.72), int(h*.72))).resize((256, 256))
    g = np.asarray(im, np.float32)/255.
    gn = (g-g.mean())/(g.std()+1e-8)          # kills global brightness/exposure
    gm = _grad(gn)
    lap = gn[1:-1,1:-1]*4 - gn[:-2,1:-1] - gn[2:,1:-1] - gn[1:-1,:-2] - gn[1:-1,2:]
    return dict(d10=float((gn<-1.0).mean()), d15=float((gn<-1.5).mean()),
                d20=float((gn<-2.0).mean()), gmean=float(gm.mean()),
                gp95=float(np.percentile(gm,95)), lapvar=float(lap.var()),
                colstd=float(gn.mean(0).std()), colmin=float(gn.mean(0).min()),
                rowstd=float(gn.mean(1).std()))

rows = []
for _, r in tqdm(clean.iterrows(), total=len(clean), desc='features'):
    p = DATA_ROOT / r.relative_path
    rows.append({'image_id': r.image_id, 'proxy': r.proxy_label,
                 'sess': r.session_group, 'fold_id': r.fold_id,
                 **colour_feats(p), **struct_feats(p)})
F = pd.DataFrame(rows)
F['y'] = F.proxy.map(tl.C2I)
print('\\nfeatures:', F.shape)
print('\\nper-class structure means (physically meaningful wear cues):')
print(F.groupby('proxy')[['d20','colstd','gmean']].mean().round(4).to_string())
print('  d20    = deep-groove shadow fraction  -> expect low > mid > high')
print('  colstd = vertical groove banding      -> expect low > mid > high')
"""),
        md("## Step 3 — Run the probes on the supplied group folds"),
        code("""# instant.
COLOUR = ['R','G','B','bright','contrast','sat','sat_p99','blueish','bright_frac','dark_frac']
STRUCT = ['d10','d15','d20','gmean','gp95','lapvar','colstd','colmin','rowstd']

def softmax(z):
    z = z - z.max(1, keepdims=True); e = np.exp(z); return e/e.sum(1, keepdims=True)

def fit(X, y, k=3, iters=4000, lr=.5, l2=1e-2):
    n, d = X.shape; W, b, Y = np.zeros((d,k)), np.zeros(k), np.eye(k)[y]
    for _ in range(iters):
        G = (softmax(X@W+b)-Y)/n; W -= lr*(X.T@G + l2*W); b -= lr*G.sum(0)
    return W, b

def probe(cols, name):
    print(f'\\n=== {name} ===')
    scores = []
    for k in (0,1,2):
        tr, va = F[F.fold_id!=k], F[F.fold_id==k]
        mu, sd = tr[cols].values.mean(0), tr[cols].values.std(0)+1e-8
        W, b = fit((tr[cols].values-mu)/sd, tr.y.values)
        pv = softmax(((va[cols].values-mu)/sd)@W+b).argmax(1)
        m, cm = tl.classification_report_dict(va.y.values, pv, None, '')
        scores.append(m['f1_macro'])
        maj = np.bincount(va.y.values, minlength=3).argmax()
        print(f'  fold {k}: n={len(va):>4}  macroF1={m["f1_macro"]:.3f}  '
              f'acc={m["acc"]:.3f}  QWK={m["qwk"]:.3f}  '
              f'(majority acc={(va.y.values==maj).mean():.3f})')
        print(f'     confusion rows=true[low,mid,high]:\\n{cm}')
    print(f'  MEAN macroF1 = {np.mean(scores):.3f}   spread {min(scores):.3f} .. {max(scores):.3f}')
    return np.mean(scores), scores

a_mean, a_folds = probe(COLOUR, 'PROBE A - COLOUR ONLY')
b_mean, b_folds = probe(STRUCT, 'PROBE B - STRUCTURE ONLY')
maj = float(np.mean([ (F[F.fold_id==k].y.values == np.bincount(F[F.fold_id!=k].y.values, minlength=3).argmax()).mean() for k in (0,1,2)]))

print('\\n' + '='*70)
print(f'FLOOR TO BEAT:  colour {a_mean:.3f}   structure {b_mean:.3f}   '
      f'-> any model must beat {max(a_mean,b_mean):.3f}')
print('Report ALL THREE FOLDS. A single-fold number from this package is not evidence.')
print('='*70)
"""),
        md("## Step 4 — HOG + SVM, and a random-initialised CNN"),
        code("""# HOG+SVM ~2-3 min; random-init CNN ~4-6 min on GPU.
# HOG+SVM is directly comparable to Petrovic et al. 2025, who used HOG features
# on a segmented tread. The random-init CNN isolates how much of a pretrained
# model's score comes from transfer alone rather than from this dataset.
import warnings; warnings.filterwarnings('ignore')
extra = []
try:
    from skimage.feature import hog
    from sklearn.svm import LinearSVC
    H = []
    for _, r in tqdm(clean.iterrows(), total=len(clean), desc='hog'):
        im = Image.open(DATA_ROOT / r.relative_path).convert('L').resize((128, 128))
        H.append(hog(np.asarray(im), orientations=9, pixels_per_cell=(16,16),
                     cells_per_block=(2,2), feature_vector=True))
    H = np.array(H); scores = []
    for k in (0,1,2):
        m_tr, m_va = (F.fold_id!=k).values, (F.fold_id==k).values
        clf = LinearSVC(C=0.01, max_iter=3000).fit(H[m_tr], F.y.values[m_tr])
        mm, _ = tl.classification_report_dict(F.y.values[m_va], clf.predict(H[m_va]), None, '')
        scores.append(mm['f1_macro']); print(f'  HOG+SVM fold {k}: macroF1={mm["f1_macro"]:.3f}')
    print(f'  HOG+SVM MEAN macroF1 = {np.mean(scores):.3f}')
    extra.append({'baseline':'hog_svm', 'f0':scores[0], 'f1':scores[1], 'f2':scores[2], 'mean':float(np.mean(scores))})
except Exception as e:
    print('HOG+SVM skipped:', e)

try:
    cfgs = [sess.config('resnet18', f, 1, technique='randinit', stage='s1',
                        pretrained=False, max_epochs=15, input_resolution=224,
                        batch_size=32, warmup_epochs=1) for f in (0,1,2)]
    sums = [tl.Trainer(c, sess).run() for c in cfgs]
    f1s = [s.get('best_val_f1_macro', float('nan')) for s in sums]
    print(f'  random-init CNN MEAN macroF1 = {np.nanmean(f1s):.3f}')
    extra.append({'baseline':'random_init_cnn','f0':f1s[0],'f1':f1s[1],'f2':f1s[2],'mean':float(np.nanmean(f1s))})
except Exception as e:
    print('random-init CNN skipped:', e)
"""),
        md("## Step 5 — Save, push, and record the floor"),
        code("""import json
from pathlib import Path
out = Path(sess.stage_dir)/'tables'; out.mkdir(parents=True, exist_ok=True)
base = pd.DataFrame([
    {'baseline':'colour_probe','f0':a_folds[0],'f1':a_folds[1],'f2':a_folds[2],'mean':a_mean},
    {'baseline':'structure_probe','f0':b_folds[0],'f1':b_folds[1],'f2':b_folds[2],'mean':b_mean},
    {'baseline':'majority_class_acc','f0':None,'f1':None,'f2':None,'mean':maj},
] + extra)
base.to_csv(out/'baselines.csv', index=False)
F.to_csv(out/'baseline_features.csv', index=False)
print(base.to_string(index=False))

sess.uploader.enqueue(out/'baselines.csv', 'tables/baselines.csv', force=True)
sess.uploader.enqueue(out/'baseline_features.csv', 'tables/baseline_features.csv', force=True)
sess.uploader.enqueue_dir(Path(sess.stage_dir)/'runs', 'runs', force=True)
sess.push_now('baselines complete')
sess.finish()
print(f'\\nFLOOR RECORDED: every model in Stage A must beat {max(a_mean,b_mean):.3f} mean macro-F1.')
""")]
    write_nb("NB01_Baselines.ipynb", c)


# ==========================================================================
# NB02..NB04 -- Stage A architecture sweep, split by family
# ==========================================================================
def stage_a_nb(name, title, archs, why):
    c = [md(f"""# {name.split('_')[0]} — Stage A: {title}

{budget_md(archs)}

## Why this group is its own notebook

{why}

Splitting Stage A by architecture family keeps each notebook inside one or two
Kaggle sessions, and means a failure in one family does not block the others.
All notebooks share the same library, the same registry and the same recipe —
so results across them are directly comparable.

> **The recipe is FIXED across the whole of Stage A.** Resolution, batch size,
> head, optimiser, schedule, sampler, epoch budget — all identical. If the
> recipe changes mid-sweep the architecture comparison stops being a
> comparison. Technique variation is Stage B's job.
"""),
         code(bootstrap_cell()),
         md("## Step 1 — Session"),
         code(SESSION_CELL),
         md("## Step 2 — Dataset"),
         code(DATA_CELL),
         md("## Step 3 — Catch up with every account"),
         code(SYNC_CELL),
         md("""## Step 4 — See the plan and the time before committing to it

If the split looks badly unbalanced, or the hours are more than you want on one
account, change `NUM_WORKERS` **now** rather than discovering it on day three."""),
         code(f"""ARCHS = {archs!r}
FOLDS = (0, 1, 2)
SEEDS = (1, 2, 3)

# ~15 s. Builds each architecture (no pretrained download) and forwards one
# batch at the resolution it will actually be fed. RAISES if any cannot.
#
# NB05 was launched on four accounts without this. All 18 dinov2 runs died on
# their first batch -- `vit_*_patch14_dinov2` is created at img_size=518 and
# its patch embedding asserts an exact match against the 392 we feed it. The
# check that would have caught it took fifteen seconds.
tl.assert_zoo_ok(ARCHS)

cfgs = sess.configs(ARCHS, FOLDS, SEEDS, technique='base')
run_ids = [c['run_id'] for c in cfgs]

est = tl.estimate_phase(run_ids, num_workers=NUM_WORKERS)
print(f"runs in this notebook : {{est['n_runs']}}")
print(f"total GPU time        : ~{{est['total_gpu_hours']:.1f}} GPU-hours")
print(f"at NUM_WORKERS={{NUM_WORKERS:<2d}}      : ~{{est['wall_clock_hours']:.1f}} h wall-clock "
      f"({{est['sessions_needed']}} Kaggle session(s) on this account)")
print()
for nw in (1, 2, 4):
    if nw > est['n_runs']:
        break
    e = tl.estimate_phase(run_ids, nw)
    print(f"  NUM_WORKERS={{nw}}: ~{{e['wall_clock_hours']:5.1f}} h wall-clock"
          + ('   <-- you' if nw == NUM_WORKERS else ''))
print()
rep = tl.shard_report(run_ids, max(NUM_WORKERS, 1))
print(rep.to_string(index=False))
print(f"imbalance: {{rep.attrs.get('imbalance', 1.0)}}x   (1.0 is perfect)")
"""),
         md("""## Step 4b — What is already on HuggingFace, and what this session will do

Read this table before every long run. It is the answer to the only question
that matters — *am I about to redo work that is already done* — taken from the
files rather than from anybody's bookkeeping.

`state` comes from the repository. `registry` comes from the run log. When they
disagree, **the repository is right**: a run the registry calls `failed`
because it hit an exception at epoch 47 still has a checkpoint at epoch 47, and
`action` will correctly say `resume`."""),
         code("""recon = sess.reconcile(run_ids)"""),
         md("""## Step 5 — Train

**Safe to stop at any moment.** SIGTERM, Ctrl-C, an uncaught exception and the
8.5-hour watchdog all trigger an immediate push before anything is lost. Start
a fresh session and re-run this notebook to continue exactly where it stopped.

Each epoch shows a live progress bar; the summary line after it carries
`val_QWK` (the ordinal metric we select on) and `dl` (the fraction of the epoch
spent waiting for data — if that is high the fix is the dataloader, not the
model).

HuggingFace receives: metrics every epoch, checkpoints every epoch, telemetry
every 10 epochs, and a **blocking push the moment each model finishes**."""),
         code("""summaries = sess.run_all(cfgs, title='Stage A')"""),
         md("""## Step 6 — Results, from HuggingFace, against the floor

`aggregate_remote()` — not `aggregate()`. The local one globs this session's
staging directory, so on four accounts each one produces a table of the eleven
runs it happened to do. Nobody ever sees all thirty-six, which is the only view
that answers anything.

Two numbers per model, and the gap between them is the point:

| | chosen by | honest? |
|---|---|---|
| `best_val_*` | the epoch with the highest val QWK | **no** — selected by looking at the 4-tyre validation fold |
| `final_val_*` | epoch 60, fixed budget | yes — nobody chose it |"""),
         code("""df = sess.aggregate_remote(run_ids)
if len(df):
    print()
    g = sess.honest_table(df)
    print('\\n\\nTrivial baselines (macro-F1 per fold):')
    print(tl.baseline_table().to_string(index=False))
else:
    print('nothing on HuggingFace yet for these run ids')
"""),
         md("""## Step 7 — Progress across ALL accounts

If `trained more than once` appears here, two accounts did the same run. That
is wasted GPU time, not a correctness problem — the results are identical."""),
         code("""import pandas as pd
sess.sync_state(run_ids, verbose=False)
state = sess.registry.latest()
rows = [{'run_id': r, 'state': state.get(r, {}).get('state', 'not started'),
         'epoch': sess.inventory.epoch(r),
         'qwk': sess.inventory.qwk(r),
         'by': state.get(r, {}).get('account')} for r in sorted(run_ids)]
prog = pd.DataFrame(rows)
print(prog.to_string(index=False))
n_done = int((prog.state == 'completed').sum())
print(f'\\n{n_done} of {len(prog)} runs finished across all accounts '
      f'({n_done/max(1,len(prog))*100:.0f}%)')
"""),
         md("## Step 8 — Finish"),
         code(FINISH_CELL)]
    write_nb(name, c)


# ==========================================================================
# NB06 -- Stage B: technique OFAT
# ==========================================================================
def nb06():
    c = [md("""# NB06 — Stage B: which techniques actually help

One factor at a time, on the architectures that led Stage A. **OFAT, not a
grid** — a 12-factor grid at 3 folds × 3 seeds is astronomically large and
uninterpretable; one factor at a time is 12 × 9 runs per architecture and every
number answers a single question.

> **OFAT cannot detect interactions.** That is a real limitation and it gets
> stated in the results, not hidden. If a factor helps one architecture and not
> another, say so.

## The factors

| # | Factor | Levels | Expectation |
|---:|---|---|---|
| 1 | head | CE · **CORAL** · regression | CORAL — classes are ordered |
| 2 | loss shaping | plain · focal · label smoothing | small |
| 3 | sampler | uniform · class-weighted · **session-balanced** | session-balanced |
| 4 | resolution | 224 · 384 · 512 · 768 | higher, up to a point |
| **5** | **ROI** | full frame · **tyre crop** | **likely the biggest single effect** |
| 6 | augmentation | dataset policy · + RandAugment | |
| 7 | transfer | ImageNet · DINOv2 · random | |
| 8 | fine-tune depth | frozen · last block · **full** | full |
| 9 | regularisation | EMA · stochastic depth · wd sweep | |
| 10 | preprocessing | raw · CLAHE · **grayscale** | grayscale is a *test*, not a gain |
| 11 | ensemble | single · seed · TTA | free gain |
| 12 | calibration | none · temperature · conformal | |

**Factor 5 first.** Frame occupancy is the strongest trivial baseline in this
dataset (0.535 mean macro-F1 from nothing but how much of the frame is tyre).
A tyre-region crop removes that shortcut outright, which makes it a **control**,
not an optimisation.

**Factor 10's grayscale arm is diagnostic.** Colour carries no wear information.
If removing it *hurts*, the model was using colour — and colour here means dirt
and factory paint stripes.
"""),
         code(bootstrap_cell()),
         md("## Step 1 — Session"), code(SESSION_CELL.replace("stage='a'", "stage='b'")),
         md("## Step 2 — Dataset"), code(DATA_CELL),
         md("## Step 3 — Catch up"), code(SYNC_CELL),
         md("""## Step 4 — Pick the Stage A winners

Chosen on **both** mean macro-F1 **and** TER_norm — not accuracy alone. A model
that scores well by looking at the background is not a model we want to tune."""),
         code('''import pandas as pd
sess.sync_state(verbose=False)
df = sess.aggregate()
if len(df) and "best_val_qwk" in df:
    top = (df[df.status == "completed"].groupby("arch")
             .agg(qwk=("best_val_qwk", "mean"), f1=("best_val_f1_macro", "mean"),
                  spread=("best_val_f1_macro", lambda x: x.max() - x.min()), n=("run_id", "size"))
             .sort_values("qwk", ascending=False).round(3))
    print(top.to_string())
    TOP3 = list(top.index[:3])
else:
    print("Stage A results not found locally -- falling back to the expected front-runners")
    TOP3 = ["convnextv2_t", "effnetv2s", "resnet50"]
print("\\nStage B architectures:", TOP3)
print("\\nfloor to beat:", tl.FLOOR, "(frame-occupancy baseline)")
'''),
         md("## Step 5 — Build the OFAT grid"),
         code('''FACTORS = {
    "head_ce":        dict(head_type="ce", loss_name="cross_entropy"),
    "head_ls":        dict(head_type="ce", loss_name="cross_entropy", label_smoothing=0.1),
    "sampler_uniform":dict(sampler_name="uniform"),
    "res224":         dict(input_resolution=224),
    "res512":         dict(input_resolution=512, batch_size=16),
    "roi_tyre":       dict(roi_mode="tyre_crop"),          # <- the control
    "transfer_random":dict(pretrained=False),
    "ft_frozen":      dict(finetune_depth="frozen"),
    "wd_low":         dict(weight_decay=0.01),
    "prep_clahe":     dict(preprocessing="clahe"),
    "prep_gray":      dict(preprocessing="grayscale"),     # <- shortcut test
    "lr_low":         dict(lr_initial=1e-4),
}
cfgs = []
for arch in TOP3:
    for name, ov in FACTORS.items():
        cfgs.extend(sess.configs([arch], (0, 1, 2), (1, 2, 3), technique=name, **ov))
run_ids = [c["run_id"] for c in cfgs]

est = tl.estimate_phase(run_ids, num_workers=NUM_WORKERS)
print(f"configs {len(FACTORS)} x archs {len(TOP3)} x 9 = {len(run_ids)} runs")
print(f"total GPU time  : ~{est['total_gpu_hours']:.0f} GPU-hours")
print(f"at {NUM_WORKERS} worker(s): ~{est['wall_clock_hours']:.0f} h wall-clock")
print()
print(tl.shard_report(run_ids, max(NUM_WORKERS, 1)).to_string(index=False))
'''),
         md("""## Step 6 — Train

**Run `roi_tyre` first if you are short on time.** It is the control that
removes the strongest known shortcut, and its result changes how every other
number should be read."""),
         code("summaries = sess.run_all(cfgs, title='Stage B OFAT')"),
         md("## Step 7 — Effect of each factor"),
         code('''import pandas as pd, numpy as np
df = sess.aggregate()
if len(df):
    d = df[df.status == "completed"]
    base = d[d.technique == "base"].groupby("arch").best_val_f1_macro.mean()
    rows = []
    for (arch, tech), g in d[d.technique != "base"].groupby(["arch", "technique"]):
        if arch not in base:
            continue
        delta = g.best_val_f1_macro.mean() - base[arch]
        rows.append({"arch": arch, "factor": tech, "n": len(g),
                     "mean_f1": round(g.best_val_f1_macro.mean(), 3),
                     "delta_vs_base": round(delta, 3),
                     "spread": round(g.best_val_f1_macro.max() - g.best_val_f1_macro.min(), 3)})
    e = pd.DataFrame(rows).sort_values("delta_vs_base", ascending=False)
    print(e.to_string(index=False))
    print("\\nSpread matters as much as the mean. A factor that lifts the mean but")
    print("widens the fold spread has probably found a better shortcut, not a better model.")
else:
    print("no completed runs yet")
'''),
         md("## Step 8 — Progress and finish"),
         code('''import pandas as pd
sess.sync_state(verbose=False)
st = sess.registry.latest()
prog = pd.DataFrame([{"run_id": r, "state": st.get(r, {}).get("state", "not started"),
                      "qwk": st.get(r, {}).get("best_qwk")} for r in sorted(run_ids)])
n = int((prog.state == "completed").sum())
print(f"{n} of {len(prog)} Stage B runs complete ({n/max(1,len(prog))*100:.0f}%)")
print(prog.head(20).to_string(index=False))
'''),
         code(FINISH_CELL)]
    write_nb("NB06_StageB_OFAT.ipynb", c)


# ==========================================================================
# NB07 -- XAI: the primary axis
# ==========================================================================
def nb07():
    c = [md("""# NB07 — XAI: where does each model actually look?

**This is the study's primary axis, not a results-section garnish.**

Accuracy is not identifiable on this dataset — four trivial baselines each score
near-perfectly on a *different* fold. Where the evidence comes from is
identifiable, and it is the property that decides whether a model survives a
tyre it has never seen.

## What gets computed, per model

| Metric | Meaning | Good |
|---|---|---|
| **TER_norm** | area-normalised attention on the tread | **> 1.0** |
| **BAR** | attention outside the tyre entirely | low |
| **SAR** | attention on factory paint stripes — a `low`-class giveaway | low |
| **DmgAR** | attention on visible damage — a `high`-class giveaway | low |
| Insertion / Deletion AUC | is the explanation faithful at all? | high / low |
| Randomisation sanity | does the map change when weights are randomised? | **must** |

## ⚠ Two things that would invalidate this

**Grad-CAM on a ViT is not the same operation as Grad-CAM on a CNN.** Several
published "Grad-CAM for ViT" methods apply gradients to attention entries rather
than averaging into channel weights — different algorithms sharing a name. Every
map here records its exact target layer and reshape, and cross-architecture
claims use the faithfulness-selected method per architecture.

**On this dataset `tread` and `tyre` are nearly the same region** (median area
ratio 0.990; 114/418 images have no visible shoulder). So **TER measures
attention on the tyre versus the background**, not tread versus shoulder. That
is still the sharpest question this data supports — frame occupancy alone scores
0.535 — but the claim must be worded that way.

**Runtime: ~15–25 min per architecture** (inference only).
"""),
         code(bootstrap_cell()),
         md("## Step 1 — Session and data"), code(SESSION_CELL.replace("stage='a'", "stage='xai'")),
         code(DATA_CELL),
         code(r"""# annotations are REQUIRED from here on -- they are the measuring instrument
assert ANN_ROOT is not None, "annotations/ not found in the attached dataset"

# Do not trust the propagated masks as supplied. Kaggle pins ONE VERSION of a
# dataset to a notebook and re-uploading does not move existing notebooks onto
# it, so which copy you get is not under your control -- and misplaced masks
# make every TER/BAR/SAR number quietly wrong rather than obviously wrong.
#
# This measures them (3 s) and, if they do not track their images, rebuilds all
# 4,180 from the 418 hand-drawn masks and the recorded transform traces (20 s).
# Both inputs are in every version of the dataset. See docs/05 Bug 16.
ANN = tl.ensure_annotations(DATA_ROOT, ann_root=ANN_ROOT, work_dir=sess.stage_dir/"annotations")
import subprocess, sys
for pkg in ("grad-cam", "opencv-python-headless"):
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", pkg], check=False)
print("XAI dependencies ready")
"""),
         md("""## Step 2 — Pre-register the hypotheses

**Do this before looking at any result.** A hypothesis invented after seeing the
scatter plot is not a hypothesis, and an examiner who knows the difference will
ask."""),
         code(r"""import json, time
from pathlib import Path
HYPOTHESES = {
 "registered_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
 "H1": "Area-normalised TER predicts cross-fold macro-F1 stability better than validation accuracy does.",
 "H2": "Models with high SAR on the low class lose more accuracy under stripe masking; "
       "symmetrically, high DmgAR on the high class loses more under damage masking.",
 "H3": "Models that beat the 0.535 frame-occupancy floor have higher TER_norm than those that do not.",
}
p = Path(sess.stage_dir) / "analysis"; p.mkdir(parents=True, exist_ok=True)
(p / "hypotheses.json").write_text(json.dumps(HYPOTHESES, indent=2))
sess.uploader.enqueue(p / "hypotheses.json", "analysis/hypotheses.json", force=True)
sess.push_now("hypotheses registered")
print(json.dumps(HYPOTHESES, indent=2))
"""),
         md("## Step 3 — Which checkpoints are available"),
         code(r"""import pandas as pd
from pathlib import Path
ck = sorted(Path(sess.stage_dir).glob("runs/*/checkpoints/ckpt_best.pt"))
print(f"local checkpoints: {len(ck)}")
if not ck:
    print("\nNone locally. Pull them from HuggingFace first:")
    print("  from huggingface_hub import snapshot_download")
    print("  snapshot_download('Shanmuk4622/tyre-wear-study', repo_type='dataset',")
    print("                    allow_patterns=['runs/a-*/checkpoints/ckpt_best.pt'])")
for c in ck[:15]:
    print("  ", c.parts[-3])
"""),
         md("""## Step 4 — Sanity-check every attribution method first

A method whose map barely changes when the model's weights are randomised is not
explaining the model — it is an edge detector. Cheap to check, and it has failed
for published methods before."""),
         code(r"""import torch, numpy as np, pandas as pd
dev = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tr_df, va_df = tl.load_split(DATA_ROOT, 0)
_, va_dl = tl.build_loaders(DATA_ROOT, tr_df, va_df, tl.RECIPE | {"batch_size": 4, "num_workers": 0})
xb, yb, _ = next(iter(va_dl)); xb = xb[:2].to(dev)

rows = []
for arch in ["resnet50", "convnextv2_t", "effnetv2s", "vit_s", "swin_t"]:
    try:
        m = tl.build_model(arch, 3, pretrained=True, head="coral").to(dev).eval()
        cam, tag = tl.make_cam(m, arch, "gradcam")
        if cam is None:
            rows.append({"arch": arch, "method": "gradcam", "tag": tag, "sanity_delta": None}); continue
        d = tl.randomisation_sanity(m, arch, xb, "gradcam")
        rows.append({"arch": arch, "method": "gradcam", "tag": tag,
                     "sanity_delta": round(float(d), 4),
                     "verdict": "PASS" if d > 0.05 else "FAIL - map barely moved"})
        del m; torch.cuda.empty_cache()
    except Exception as e:
        rows.append({"arch": arch, "method": "gradcam", "tag": f"{type(e).__name__}", "sanity_delta": None})
print(pd.DataFrame(rows).to_string(index=False))
print("\nsanity_delta = mean |saliency change| after randomising the target layer.")
print("Below ~0.05 means the method is not reading the model. Do not use it.")
"""),
         md("## Step 5 — Compute TER / BAR / SAR / DmgAR for every checkpoint"),
         code(r"""import torch, numpy as np, pandas as pd
from pathlib import Path
from tqdm.auto import tqdm

def evidence_for_run(run_dir: Path, n_images=120):
    ck = run_dir / "checkpoints" / "ckpt_best.pt"
    if not ck.exists(): return None
    st = torch.load(ck, map_location="cpu", weights_only=False)
    cfg = st["config"]; arch = cfg["arch"]
    model = tl.build_model(arch, 3, pretrained=False, head=cfg["head_type"])
    model.load_state_dict(st["model"]); model = model.to(dev).eval()
    cam, tag = tl.make_cam(model, arch, "gradcam")
    if cam is None: return None

    tr_df, va_df = tl.load_split(DATA_ROOT, cfg["fold"])
    sub = va_df.head(n_images)
    tf = tl.build_transforms(cfg["input_resolution"], False, cfg.get("preprocessing", "raw"))
    from PIL import Image
    out = []
    for r in tqdm(list(sub.itertuples()), desc=run_dir.name, leave=False):
        mask = tl.load_mask(ANN, r.image_id, r.image_kind)
        if mask is None: continue
        x = tf(Image.open(DATA_ROOT / r.relative_path).convert("RGB")).unsqueeze(0).to(dev)
        try: sal = cam(input_tensor=x)[0]
        except Exception: continue
        e = tl.evidence_metrics(sal, mask)
        out.append({"run_id": run_dir.name, "arch": arch, "fold": cfg["fold"],
                    "seed": cfg["seed"], "image_id": r.image_id,
                    "proxy_label": r.proxy_label, "method": tag, **e})
    del model, cam; torch.cuda.empty_cache()
    return pd.DataFrame(out)

frames = []
for rd in sorted(Path(sess.stage_dir).glob("runs/a-*")):
    df = evidence_for_run(rd)
    if df is not None and len(df):
        frames.append(df)
        (rd / "xai").mkdir(exist_ok=True)
        df.to_csv(rd / "xai" / "evidence.csv", index=False)
        sess.uploader.enqueue(rd / "xai" / "evidence.csv", f"runs/{rd.name}/xai/evidence.csv", force=True)

if frames:
    ev = pd.concat(frames, ignore_index=True)
    out = Path(sess.stage_dir) / "tables"; out.mkdir(parents=True, exist_ok=True)
    ev.to_csv(out / "xai_evidence_all.csv", index=False)
    sess.uploader.enqueue(out / "xai_evidence_all.csv", "tables/xai_evidence_all.csv", force=True)
    print(f"\n{len(ev)} image-level evidence rows from {ev.run_id.nunique()} runs")
    summ = (ev.groupby("arch")[["ter_norm", "ter", "bar", "sar", "dmgar", "edi"]]
              .mean().round(3).sort_values("ter_norm", ascending=False))
    print("\n" + summ.to_string())
    print("\nTER_norm > 1.0 = attends to tread MORE than its area share.")
    print("TER_norm ~ 1.0 = no preference -- the model is spreading attention evenly.")
else:
    print("no evidence computed -- are there checkpoints in", sess.stage_dir, "?")
sess.push_now("XAI evidence complete")
"""),
         md("## Step 6 — Faithfulness, and the headline plot"),
         code(r"""import matplotlib.pyplot as plt
import pandas as pd
try:
    df = sess.aggregate()
    acc = df[df.status == "completed"].groupby("arch").best_val_f1_macro.mean()
    ter = ev.groupby("arch").ter_norm.mean()
    j = pd.DataFrame({"macro_f1": acc, "ter_norm": ter}).dropna()
    fig, ax = plt.subplots(figsize=(7, 5.5))
    ax.scatter(j.ter_norm, j.macro_f1, s=70)
    for k, r in j.iterrows():
        ax.annotate(k, (r.ter_norm, r.macro_f1), fontsize=8,
                    xytext=(4, 4), textcoords="offset points")
    ax.axhline(tl.FLOOR, ls="--", c="crimson",
               label=f"frame-occupancy floor ({tl.FLOOR})")
    ax.axvline(1.0, ls=":", c="grey", label="TER_norm = 1 (no preference)")
    ax.set_xlabel("TER_norm  —  attention on tread, area-normalised")
    ax.set_ylabel("mean macro-F1 over 3 folds")
    ax.set_title("Figure 1  —  accuracy vs evidence quality")
    ax.legend(fontsize=8); ax.grid(alpha=.3); plt.tight_layout()
    p = Path(sess.stage_dir) / "analysis" / "fig01_accuracy_vs_ter.png"
    p.parent.mkdir(parents=True, exist_ok=True); plt.savefig(p, dpi=150)
    sess.uploader.enqueue(p, "analysis/figures/fig01_accuracy_vs_ter.png", force=True)
    plt.show()
    print("\nUpper-right = accurate AND looking at the tread. That is the quadrant we want.")
    print("Upper-left  = accurate while looking elsewhere. That is a shortcut.")
except Exception as e:
    print("figure skipped:", e)
"""),
         code(FINISH_CELL.replace("run_ids", "[p.name for p in sorted(Path(sess.stage_dir).glob('runs/a-*'))]"))]
    write_nb("NB07_XAI.ipynb", c)


# ==========================================================================
# NB08 -- Shortcut stress tests
# ==========================================================================
def nb08():
    c = [md("""# NB08 — Shortcut stress tests

Interventions, not correlations. Each answers a **causal** question: if I remove
this cue, does the model still work?

## The interventions

| Test | What it removes | Reading |
|---|---|---|
| **Shuffled labels** | the signal itself | **above chance ⇒ pipeline leak. Stop everything** |
| Background blanking | everything outside the tyre | drop ⇒ background dependence |
| Background swap | replaces it with another session's | drop ⇒ background dependence |
| **Tyre crop** | frame occupancy, the strongest known shortcut | rise ⇒ context was harmful |
| **Stripe masking** | factory paint on `low` (67 images) | drop in `low` recall ⇒ marking dependence |
| **Damage masking** | visible damage on `high` (63 images) | drop in `high` recall ⇒ damage dependence |
| Grayscale | colour | drop ⇒ colour dependence, and colour is not a wear cue |

## Why stripe *and* damage

The annotations showed these are **perfectly class-separable**:

| | `marking` | `damage` |
|---|---:|---:|
| low | **67** | 0 |
| mid | 0 | 0 |
| high | 0 | **63** |

A rule of `marking→low, damage→high, else→mid` scores 0.978 on fold 0. Testing
one without the other measures half the problem.

**Run the shuffled-label control first.** If it scores above chance there is a
leak in the pipeline and nothing else matters until it is found.

**Runtime: ~30–45 min** (inference only, except the shuffled-label run).
"""),
         code(bootstrap_cell()),
         md("## Step 1 — Session and data"), code(SESSION_CELL.replace("stage='a'", "stage='stress'")),
         code(DATA_CELL),
         code("""assert ANN_ROOT is not None, 'annotations/ required for masking interventions'

# Same as NB07: measure the supplied masks, rebuild them if they are misplaced.
# A stress test that masks the wrong pixels measures nothing.
ANN = tl.ensure_annotations(DATA_ROOT, ann_root=ANN_ROOT, work_dir=sess.stage_dir/'annotations')"""),
         md("""## Step 2 — The shuffled-label control

Train with permuted labels. It **must** land at chance (macro-F1 ≈ 0.33). If it
does not, something is leaking the answer and every other result in the study is
suspect."""),
         code('''import numpy as np, pandas as pd
# 12 quick epochs is plenty -- we are testing for a leak, not training a model.
cfg = sess.config("resnet18", 0, 1, technique="shufflectl", stage="stress",
                  max_epochs=12, input_resolution=224, batch_size=32, warmup_epochs=1)

_orig = tl.load_split
def _shuffled(root, fold):
    tr, va = _orig(root, fold)
    rng = np.random.default_rng(0)
    tr = tr.copy(); tr["proxy_label"] = rng.permutation(tr["proxy_label"].values)
    return tr, va
tl.load_split = _shuffled
try:
    s_ctl = tl.Trainer(cfg, sess).run()
finally:
    tl.load_split = _orig

f1 = s_ctl.get("best_val_f1_macro", float("nan"))
print(f"\\nshuffled-label macro-F1 = {f1:.3f}   (chance ~ 0.33)")
print("PASS -- no leak detected" if f1 < 0.45 else
      "*** FAIL -- ABOVE CHANCE. There is a leak. Stop and find it before trusting anything. ***")
'''),
         md("## Step 3 — The intervention transforms"),
         code('''import numpy as np, torch
from PIL import Image

def apply_intervention(img_np, mask, kind, other_bg=None):
    """img_np HxWx3 uint8, mask HxW indexed. Returns modified image."""
    out = img_np.copy()
    if kind == "bg_blank":
        out[tl.region_background(mask)] = 128
    elif kind == "bg_swap" and other_bg is not None:
        bg = tl.region_background(mask)
        out[bg] = other_bg[bg]
    elif kind == "tyre_crop":
        ys, xs = np.where(tl.region_tyre(mask))
        if len(xs):
            out = out[ys.min():ys.max()+1, xs.min():xs.max()+1]
    elif kind == "mask_marking":
        r = tl.region_marking(mask)
        if r.any(): out[r] = np.median(out[tl.region_tread(mask) & ~r], axis=0)
    elif kind == "mask_damage":
        r = tl.region_damage(mask)
        if r.any(): out[r] = np.median(out[tl.region_tyre(mask) & ~r], axis=0)
    elif kind == "grayscale":
        g = out.mean(2, keepdims=True); out = np.repeat(g, 3, 2).astype(np.uint8)
    return out

INTERVENTIONS = ["none", "bg_blank", "bg_swap", "tyre_crop",
                 "mask_marking", "mask_damage", "grayscale"]
print("interventions:", INTERVENTIONS)
'''),
         md("## Step 4 — Evaluate every top model under every intervention"),
         code('''import torch, numpy as np, pandas as pd
from pathlib import Path
from PIL import Image
from tqdm.auto import tqdm
dev = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def eval_under(run_dir, kind, n=None):
    ck = run_dir / "checkpoints" / "ckpt_best.pt"
    if not ck.exists(): return None
    st = torch.load(ck, map_location="cpu", weights_only=False); cfg = st["config"]
    model = tl.build_model(cfg["arch"], 3, pretrained=False, head=cfg["head_type"])
    model.load_state_dict(st["model"]); model = model.to(dev).eval()
    tr_df, va_df = tl.load_split(DATA_ROOT, cfg["fold"])
    if n: va_df = va_df.head(n)
    tf = tl.build_transforms(cfg["input_resolution"], False, cfg.get("preprocessing", "raw"))
    bgs = [np.asarray(Image.open(DATA_ROOT / r.relative_path).convert("RGB"))
           for r in va_df.sample(min(5, len(va_df)), random_state=0).itertuples()]
    P, Y = [], []
    with torch.no_grad():
        for i, r in enumerate(va_df.itertuples()):
            m = tl.load_mask(ANN, r.image_id, r.image_kind)
            if m is None: continue
            a = np.asarray(Image.open(DATA_ROOT / r.relative_path).convert("RGB"))
            if m.shape != a.shape[:2]: continue
            a = apply_intervention(a, m, kind, bgs[i % len(bgs)])
            x = tf(Image.fromarray(a)).unsqueeze(0).to(dev)
            with tl._autocast(dev):
                lg = model(x)
            pr = tl.CoralHead.predict(lg) if cfg["head_type"] == "coral" else lg.argmax(1)
            P.append(int(pr)); Y.append(tl.C2I[r.proxy_label])
    del model; torch.cuda.empty_cache()
    if not P: return None
    m_, _ = tl.classification_report_dict(np.array(Y), np.array(P), None, "")
    return {"run_id": run_dir.name, "arch": cfg["arch"], "fold": cfg["fold"],
            "intervention": kind, "n": len(P), **{k: round(v, 4) for k, v in m_.items()
                                                  if k in ("f1_macro","acc","recall_low","recall_high","qwk")}}

runs = sorted(Path(sess.stage_dir).glob("runs/a-*"))[:6]
rows = []
for rd in tqdm(runs, desc="models"):
    for kind in INTERVENTIONS:
        r = eval_under(rd, kind)
        if r: rows.append(r)
S = pd.DataFrame(rows)
if len(S):
    out = Path(sess.stage_dir) / "tables"; out.mkdir(parents=True, exist_ok=True)
    S.to_csv(out / "stress_tests.csv", index=False)
    sess.uploader.enqueue(out / "stress_tests.csv", "tables/stress_tests.csv", force=True)
    piv = S.pivot_table(index="arch", columns="intervention", values="f1_macro")
    if "none" in piv:
        delta = piv.sub(piv["none"], axis=0).drop(columns=["none"]).round(3)
        print("Delta macro-F1 vs no intervention (negative = the model depended on it)\\n")
        print(delta.to_string())
        print("\\ntyre_crop POSITIVE  -> context was hurting; the crop is a real fix")
        print("mask_marking NEGATIVE on low recall -> the model reads factory paint")
        print("mask_damage  NEGATIVE on high recall -> the model reads damage, not wear")
else:
    print("no checkpoints found to stress-test")
sess.push_now("stress tests complete")
'''),
         md("## Step 5 — Finish"), code(FINISH_CELL.replace("run_ids", "[cfg['run_id']]"))]
    write_nb("NB08_StressTests.ipynb", c)


# ==========================================================================
# NB09 -- Ensembles, calibration, conformal
# ==========================================================================
def nb09():
    c = [md("""# NB09 — Ensembles, calibration and an honest "I don't know"

Reuses checkpoints already trained, so this stage is nearly free.

| Step | What | Why |
|---|---|---|
| Seed ensemble | average logits over the 3 seeds | usually the cheapest real gain |
| Architecture ensemble | top-3 architectures | does diversity help? |
| TTA | horizontal flip + multi-scale | **flip is safe for this task only** — banned for any signed toe/camber work |
| Temperature scaling | one parameter, fitted on held-out data | fixes overconfidence |
| **Conformal prediction** | prediction *sets* with a coverage guarantee | gives the `uncertain` outcome |

## Why conformal matters here

The dataset's own guidance asks for an `uncertain / request another frame`
outcome. Conformal prediction delivers exactly that, with a distribution-free
coverage guarantee, in about five lines.

Given four trivial baselines each score near-perfectly on a different fold, a
model that can say "I don't know" is worth more than one that always answers.

**Runtime: ~15 min.**
"""),
         code(bootstrap_cell()),
         md("## Step 1 — Session and data"), code(SESSION_CELL.replace("stage='a'", "stage='ens'")),
         code(DATA_CELL),
         md("## Step 2 — Gather per-sample predictions"),
         code('''import pandas as pd
from pathlib import Path
frames = []
for f in sorted(Path(sess.stage_dir).glob("runs/*/per_sample/predictions.parquet")):
    d = pd.read_parquet(f); d["run_id"] = f.parts[-3]; frames.append(d)
if frames:
    P = pd.concat(frames, ignore_index=True)
    P["arch"] = P.run_id.str.split("-").str[1]
    P["fold"] = P.run_id.str.extract(r"-f(\\d)-").astype(int)
    P["seed"] = P.run_id.str.extract(r"-s(\\d)$").astype(int)
    print(f"{len(P)} predictions from {P.run_id.nunique()} runs, "
          f"{P.arch.nunique()} architectures")
    print(P.groupby("arch").run_id.nunique().to_string())
else:
    P = pd.DataFrame(); print("no per-sample predictions found")
'''),
         md("## Step 3 — Seed and architecture ensembles"),
         code('''import numpy as np
PROB = ["prob_low", "prob_mid", "prob_high"]

def score(df, group):
    out = []
    for keys, g in df.groupby(group):
        avg = g.groupby("image_id")[PROB].mean()
        truth = g.groupby("image_id")["true"].first().loc[avg.index]
        pred = avg.values.argmax(1)
        m, _ = tl.classification_report_dict(truth.values, pred, avg.values, "")
        out.append({"group": keys, "n": len(avg),
                    "f1_macro": round(m["f1_macro"], 3), "qwk": round(m["qwk"], 3),
                    "ece": round(m.get("ece", float("nan")), 3)})
    return pd.DataFrame(out)

if len(P):
    print("single runs (per arch, fold, seed):")
    print(score(P, ["arch", "fold", "seed"]).groupby("group").f1_macro.mean().describe().round(3).to_string())
    print("\\nSEED ENSEMBLE (average over the 3 seeds):")
    print(score(P, ["arch", "fold"]).to_string(index=False))
    print("\\nARCHITECTURE ENSEMBLE (all archs, per fold):")
    print(score(P, ["fold"]).to_string(index=False))
    print(f"\\nfloor: {tl.FLOOR} (frame occupancy). Compare honestly.")
'''),
         md("""## Step 4 — Conformal prediction sets

Split conformal: take the calibration residuals, find the quantile, and emit the
set of classes whose score exceeds it. Coverage is guaranteed under
exchangeability — which fold-level distribution shift violates, so we report the
**empirical** coverage rather than assuming the nominal one."""),
         code('''import numpy as np
def conformal(cal_probs, cal_true, test_probs, alpha=0.10):
    scores = 1 - cal_probs[np.arange(len(cal_true)), cal_true]     # non-conformity
    n = len(scores)
    q = np.quantile(scores, min(1.0, np.ceil((n + 1) * (1 - alpha)) / n), method="higher")
    return (1 - test_probs) <= q, q

if len(P):
    rows = []
    for fold, g in P.groupby("fold"):
        gi = g.groupby("image_id")
        probs = gi[PROB].mean().values; truth = gi["true"].first().values
        idx = np.random.default_rng(0).permutation(len(truth))
        half = len(idx) // 2
        cal, tst = idx[:half], idx[half:]
        sets, q = conformal(probs[cal], truth[cal], probs[tst], alpha=0.10)
        cover = float(sets[np.arange(len(tst)), truth[tst]].mean())
        size = float(sets.sum(1).mean())
        rows.append({"fold": fold, "n_test": len(tst), "q": round(float(q), 3),
                     "coverage@90%": round(cover, 3), "mean_set_size": round(size, 2),
                     "abstain_rate": round(float((sets.sum(1) > 1).mean()), 3)})
    C = pd.DataFrame(rows)
    print(C.to_string(index=False))
    print("\\ncoverage should land near 0.90. Mean set size > 1 means the model is")
    print("declining to commit -- that IS the 'uncertain / request another frame' outcome.")
    out = Path(sess.stage_dir) / "tables"; out.mkdir(parents=True, exist_ok=True)
    C.to_csv(out / "conformal.csv", index=False)
    sess.uploader.enqueue(out / "conformal.csv", "tables/conformal.csv", force=True)
'''),
         md("## Step 5 — Finish"), code("sess.push_now('ensembles complete')\nsess.finish()")]
    write_nb("NB09_Ensembles_Calibration.ipynb", c)


# ==========================================================================
# NB10 -- Analysis and the paper figures
# ==========================================================================
def nb10():
    c = [md("""# NB10 — Analysis: the tables and figures for the paper

Pulls everything from HuggingFace, builds the master tables, runs the statistics,
and renders every figure.

## The figures

| # | Figure | Question it answers |
|---|---|---|
| 1 | Accuracy vs TER_norm, Pareto | **Do accurate models look at the tread?** |
| 2 | Per-fold macro-F1, all architectures, with all four baselines drawn | How much of this is noise? |
| 3 | Saliency panels — same image, every architecture | Qualitative, immediately legible |
| 4 | Stress-test matrix, models × interventions | What does each model depend on? |
| 5 | **Does TER predict cross-fold stability better than accuracy?** | **The pre-registered claim** |
| 6 | Technique OFAT effect sizes with CIs | What actually helps on small data |
| 7 | Faithfulness across methods × architectures | Which explanations to trust |
| 8 | Convergence — best epoch by architecture | Free finding from the fixed budget |
| 9 | Energy per architecture | Free finding from the telemetry |
| 10 | Per-session accuracy heat map | Where single-tyre memorisation shows |

**Report H1–H3 outcomes whatever they are.** A pre-registered hypothesis that
fails is a finding; one invented after the plot is not.

**Runtime: ~10 min.**
"""),
         code(bootstrap_cell()),
         md("## Step 1 — Session"), code(SESSION_CELL.replace("stage='a'", "stage='analysis'")),
         md("## Step 2 — Pull every result from HuggingFace"),
         code('''from huggingface_hub import snapshot_download
from pathlib import Path
import pandas as pd

LOCAL = Path("/kaggle/temp/study_pull")
try:
    snapshot_download("Shanmuk4622/tyre-wear-study", repo_type="dataset",
                      local_dir=str(LOCAL), token=sess.uploader.token,
                      allow_patterns=["runs/*/metrics/*.csv", "runs/*/summary.json",
                                      "runs/*/split_health.json", "runs/*/xai/*.csv",
                                      "tables/*.csv", "registry/events/*.jsonl"])
    print("pulled to", LOCAL)
except Exception as e:
    print("pull failed:", e); LOCAL = Path(sess.stage_dir)

runs = []
for f in sorted(LOCAL.glob("runs/*/metrics/final.csv")):
    try: runs.append(pd.read_csv(f))
    except Exception: pass
R = pd.concat(runs, ignore_index=True) if runs else pd.DataFrame()
print(f"\\n{len(R)} runs   {R.arch.nunique() if len(R) else 0} architectures")
if len(R):
    print(R.groupby("stage").run_id.count().to_string())
'''),
         md("## Step 3 — Master table"),
         code('''import numpy as np
if len(R):
    d = R[R.status == "completed"]
    T = (d.groupby("arch").agg(
            n=("run_id", "size"),
            f1_mean=("best_val_f1_macro", "mean"), f1_min=("best_val_f1_macro", "min"),
            f1_max=("best_val_f1_macro", "max"), qwk_mean=("best_val_qwk", "mean"),
            epochs=("epochs_trained", "mean"), wall_h=("total_wall_seconds", lambda x: x.mean()/3600),
            energy_wh=("total_energy_wh", "mean"))
          .assign(spread=lambda x: x.f1_max - x.f1_min)
          .sort_values("f1_mean", ascending=False).round(3))
    print(T.to_string())
    print(f"\\nFLOOR = {tl.FLOOR} (frame occupancy). Anything at or below it learned nothing new.")
    above = (T.f1_mean > tl.FLOOR).sum()
    print(f"{above}/{len(T)} architectures beat the floor.")
    print("\\nSPREAD is the column to read. High mean with high spread means the model")
    print("found a shortcut that works on one fold.")
    out = Path(sess.stage_dir) / "tables"; out.mkdir(parents=True, exist_ok=True)
    T.to_csv(out / "master_architectures.csv")
    sess.uploader.enqueue(out / "master_architectures.csv", "tables/master_architectures.csv", force=True)
'''),
         md("## Step 4 — Figure 2: per-fold results against every baseline"),
         code('''import matplotlib.pyplot as plt
import numpy as np
if len(R):
    d = R[R.status == "completed"]
    piv = d.pivot_table(index="arch", columns="fold", values="best_val_f1_macro").sort_index()
    fig, ax = plt.subplots(figsize=(11, 5.5))
    w = 0.26
    x = np.arange(len(piv))
    for i, f in enumerate(sorted(piv.columns)):
        ax.bar(x + (i - 1) * w, piv[f], w, label=f"fold {f}")
    cols = {"frame_occupancy": "crimson", "colour_probe": "darkorange",
            "structure_probe": "seagreen", "annotation_sidechannel": "purple"}
    for k, c_ in cols.items():
        ax.axhline(tl.BASELINES[k]["mean"], ls="--", lw=1.2, c=c_,
                   label=f"{k} ({tl.BASELINES[k]['mean']})")
    ax.set_xticks(x); ax.set_xticklabels(piv.index, rotation=45, ha="right")
    ax.set_ylabel("macro-F1"); ax.set_title("Figure 2 — per-fold macro-F1 vs trivial baselines")
    ax.legend(fontsize=7, ncol=2); ax.grid(axis="y", alpha=.3); plt.tight_layout()
    p_ = Path(sess.stage_dir) / "analysis" / "fig02_perfold.png"
    p_.parent.mkdir(parents=True, exist_ok=True); plt.savefig(p_, dpi=150)
    sess.uploader.enqueue(p_, "analysis/figures/fig02_perfold.png", force=True)
    plt.show()
    print("Every dashed line is a model with no learning in it at all.")
'''),
         md("""## Step 5 — Figure 5: the pre-registered test

**H1: does TER_norm predict cross-fold stability better than accuracy does?**

If it does, evidence quality is the better model-selection criterion on small
data — which is the study's central claim. If it does not, we report that."""),
         code('''import numpy as np, pandas as pd
try:
    ev = pd.read_csv(LOCAL / "tables" / "xai_evidence_all.csv")
    ter = ev.groupby("arch").ter_norm.mean()
    d = R[R.status == "completed"]
    per = d.groupby("arch").best_val_f1_macro
    j = pd.DataFrame({"ter_norm": ter, "acc": per.mean(),
                      "stability": -(per.max() - per.min())}).dropna()   # higher = more stable
    def pearson(a, b):
        a, b = np.asarray(a, float), np.asarray(b, float)
        return float(((a-a.mean())*(b-b.mean())).mean() / (a.std()*b.std() + 1e-12))
    r_ter = pearson(j.ter_norm, j.stability)
    r_acc = pearson(j.acc, j.stability)
    print(f"n architectures            : {len(j)}")
    print(f"corr(TER_norm, stability)  : {r_ter:+.3f}")
    print(f"corr(accuracy, stability)  : {r_acc:+.3f}")
    print()
    if abs(r_ter) > abs(r_acc):
        print(f"H1 SUPPORTED — TER_norm tracks cross-fold stability more closely than accuracy.")
    else:
        print(f"H1 NOT SUPPORTED — accuracy tracks stability at least as well.")
    print("\\nReport this either way. n is small, so treat it as indicative, not decisive.")
    j.round(3).to_csv(Path(sess.stage_dir)/"tables"/"h1_test.csv")
except Exception as e:
    print("needs NB07 output (tables/xai_evidence_all.csv):", e)
'''),
         md("## Step 6 — Free findings from the telemetry"),
         code('''import matplotlib.pyplot as plt
if len(R):
    d = R[R.status == "completed"]
    fig, axes = plt.subplots(1, 3, figsize=(15, 4))
    for ax, (col, title, unit) in zip(axes, [
            ("best_epoch", "Figure 8 — where the best epoch lands", "epoch"),
            ("total_energy_wh", "Figure 9 — energy per run", "Wh"),
            ("peak_ram_gb", "peak RAM", "GB")]):
        if col in d:
            g = d.groupby("arch")[col].mean().sort_values()
            ax.barh(g.index, g.values); ax.set_xlabel(unit); ax.set_title(title, fontsize=10)
            ax.grid(axis="x", alpha=.3)
    plt.tight_layout()
    p_ = Path(sess.stage_dir) / "analysis" / "fig08_09_telemetry.png"
    plt.savefig(p_, dpi=150); sess.uploader.enqueue(p_, "analysis/figures/fig08_09_telemetry.png", force=True)
    plt.show()
    print("Best-epoch position is a free finding from the fixed 60-epoch budget:")
    print("if one architecture peaks at 25 and another at 58, that is a convergence")
    print("result nobody had to run an extra experiment for.")
'''),
         md("## Step 7 — Figure 10: per-session accuracy, where memorisation shows"),
         code('''import pandas as pd, numpy as np, matplotlib.pyplot as plt
rows = []
for f in sorted(LOCAL.glob("runs/*/metrics/epochs.csv")):
    try:
        e = pd.read_csv(f)
        if not len(e): continue
        best = e.loc[e.val_qwk.idxmax()]
        for c in e.columns:
            if c.startswith("val_acc_session_"):
                rows.append({"run_id": f.parts[-3], "arch": best.get("arch"),
                             "session": c.replace("val_acc_session_", ""), "acc": best[c]})
    except Exception: pass
if rows:
    S = pd.DataFrame(rows).dropna()
    piv = S.pivot_table(index="arch", columns="session", values="acc")
    fig, ax = plt.subplots(figsize=(12, max(3, .45*len(piv))))
    im = ax.imshow(piv.values, aspect="auto", vmin=0, vmax=1, cmap="RdYlGn")
    ax.set_xticks(range(len(piv.columns)))
    ax.set_xticklabels([c[:22] for c in piv.columns], rotation=60, ha="right", fontsize=7)
    ax.set_yticks(range(len(piv.index))); ax.set_yticklabels(piv.index, fontsize=8)
    plt.colorbar(im, label="per-session accuracy")
    ax.set_title("Figure 10 — accuracy per validation tyre")
    plt.tight_layout()
    p_ = Path(sess.stage_dir)/"analysis"/"fig10_per_session.png"
    plt.savefig(p_, dpi=150); sess.uploader.enqueue(p_, "analysis/figures/fig10_per_session.png", force=True)
    plt.show()
    print("A column that is red for every model is a tyre nobody generalises to.")
    print("A model green everywhere but on one column has memorised the others.")
else:
    print("no per-session columns found")
'''),
         md("## Step 8 — Push everything"),
         code("sess.uploader.enqueue_dir(Path(sess.stage_dir)/'analysis', 'analysis', force=True)\nsess.uploader.enqueue_dir(Path(sess.stage_dir)/'tables', 'tables', force=True)\nsess.push_now('analysis complete')\nsess.finish()")]
    write_nb("NB10_Analysis_Figures.ipynb", c)


if __name__ == "__main__":
    print(f"library: {LIB.stat().st_size/1024:.0f} KB\n")
    nb00()
    nb01()
    stage_a_nb("NB02_StageA_CNN_classic.ipynb", "classical CNNs",
               ["resnet50", "resnext50", "densenet121", "vgg16bn"],
               "The field's reference points, and Grad-CAM's native home. They are "
               "cheap, they are what every prior tyre paper used, and VGG-16 in "
               "particular is where Grad-CAM was defined — which makes it a useful "
               "anchor for the XAI comparison in Stage E even though its accuracy "
               "will not lead.")
    stage_a_nb("NB03_StageA_CNN_modern.ipynb", "modern CNNs",
               ["convnextv2_t", "effnetv2s", "regnety016", "mobilenetv4"],
               "The expected front-runners. Modern CNNs still lead under limited data "
               "and compute, and this dataset is small — 418 real images from 12 "
               "tyres. ConvNeXt-V2 and EfficientNetV2 are the two most likely to top "
               "the accuracy table, which makes them the likely candidates for the "
               "Stage B technique sweep. ConvNeXt-V2-S is intentionally absent: timm "
               "has no pretrained Small weights, and the nine historical run ids were "
               "proved to contain an emergency ResNet-18 substitution.")
    stage_a_nb("NB04_StageA_Transformer.ipynb", "transformers and hybrids",
               ["vit_s", "deit3_s", "swin_t", "swin_s", "coatnet0", "maxvit_t"],
               "A genuinely different inductive bias: no built-in locality, learned "
               "instead from data. At this data scale they are expected to "
               "underperform — and demonstrating that cleanly, with a matched recipe "
               "and 3 folds x 3 seeds, is a legitimate result rather than a failure.\n\n"
               "> `swin_t`, `swin_s` and `coatnet0` are **fixed-window at 224** and "
               "are run at 224 here. They are excluded from the Stage B resolution "
               "sweep for that reason, and the limitation is recorded in the results "
               "table rather than hidden.")
    stage_a_nb("NB05_StageA_Foundation.ipynb", "self-supervised and foundation backbones",
               ["dinov2_s", "dinov2_b", "clip_b16"],
               "Published work on industrial inspection found frozen self-supervised "
               "features give **no clear advantage** on RGB tasks, while **fully "
               "fine-tuned** SSL initialisation is the strongest option available. "
               "We test that claim on tyres. Whether it replicates or not, it is a "
               "clean, citable sub-result — and it settles a question the team would "
               "otherwise argue about from priors.")
    # Post-Stage-A notebooks are evidence-gated and are generated separately so
    # they can be rebuilt without erasing executed NB00--NB05 outputs.
    from build_later_notebooks import build_later
    build_later(globals())
    print("\nall notebooks generated")
